[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "EnhancedSettings"
description = "A mod that enhances gameplay with four independent features: Disable FOV changes when aiming or sprinting for stable vision, Toggle Aim mode for hands-free aiming with auto-sprint resume, and Toggle Crouch for easy slide control. Fully configurable."
websiteUrl = "https://github.com/Little-Sparroh/EnhancedSettings"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/EnhancedSettings.dll"
target = "BepInEx/plugins/EnhancedSettings.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]
